FROM ghcr.io/kevinpan45/action-box:latest

# install python 3.9
RUN apt update && apt install software-properties-common && add-apt-repository ppa:deadsnakes/ppa && apt-get install -y python3.9 python3.9-dev python3.9-distutils python3.9-venv