name: Build Action Box

on:
  workflow_dispatch

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Push to Docker Hub
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: kevinpan45/action-box:latest
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        dockerfile: ./action-box/Dockerfile
