name: Build Customize WSL Distro

on:
  workflow_dispatch

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Customize WSL Distro
      working-directory: ./customize-wsl-distro
      run: docker build . --tag kevinpan45/ubuntu2004-wsl:latest
    - name: Push to Docker Hub
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: kevinpan45/ubuntu2004-wsl:latest
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
