name: Build Customize WSL Distro

on:
  workflow_dispatch:
    inputs:
      version: 
        description: 'Release version publish to GitHub Packages'
        required: true
        default: 'latest'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Push to Docker Hub
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: kevinpan45/wsl-kp45-ubuntu:latest
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        dockerfile: ./customize-wsl-distro/Dockerfile
